# Build settings
markdown: kramdown

# Site options
url: https://escornabot.com
baseurl: /

exclude:
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

collections:
  doc:
    permalink: /:path
    output: true

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

sass:
  style: compressed
