# Build settings
markdown: kramdown

# Site options
baseurl: /

exclude:
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Plugins
gems: 
  - jekyll-multiple-languages-plugin
  - jekyll-paginate

# Languages
languages:
  - en
  - en
  - es
  - gl

exclude_from_localizations:
  - css
  - js
  - img

